version: '3'

services:
  terraform:
    image: quay.io/azavea/terraform:0.11.7
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-rand}
      - GIT_COMMIT=${GIT_COMMIT:-latest}
      - FASTAI_DEBUG=1
      - FASTAI_SETTINGS_BUCKET=${FASTAI_SETTINGS_BUCKET:-jcochrane-fastai-environment-config-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
