#!/bin/bash

set -e

if [[ -n "${FASTAI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Start a console on your EC2 instance.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        INSTANCE_ID=$(docker-compose \
            run --rm --workdir "/usr/local/src/deployment/terraform" \
            --entrypoint terraform \
            terraform state show "aws_instance.fastai" |\
                grep -E " i-[a-zA-Z0-9]{10,}" | cut -d " " -f 42 | tr -d '\r')

        INSTANCE_PUBLIC_DNS=$(aws ec2 describe-instances \
            --instance-ids ${INSTANCE_ID} \
            --query 'Reservations[].Instances[].PublicDnsName' | jq -r .[0])

        ssh ubuntu@$INSTANCE_PUBLIC_DNS
    fi
fi
