#!/bin/bash

set -e

if [[ -n "${FASTAI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Attempts to setup the project's development environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        INSTANCE_ID=$(docker-compose \
            -f docker-compose.ci.yml \
            run --rm --workdir "/usr/local/src/deployment/terraform" \
            --entrypoint terraform \
            terraform output instance_id | tr -d '\r')

        function stop_instance() {
            aws --profile rand ec2 stop-instances --instance-ids "${INSTANCE_ID}"
        }

        trap "{ stop_instance; exit 130; }" SIGINT SIGTERM

        aws --profile rand ec2 start-instances --instance-ids "${INSTANCE_ID}"

        echo "Instance started -- press Ctrl+C to exit..."

        while :
        do
            sleep 60
        done
    fi
fi
