#!/bin/bash

set -e

if [[ -n "${FASTAI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Attempts to setup the project's development environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose \
            -f docker-compose.ci.yml \
            run --rm \
            terraform ./scripts/infra plan

        docker-compose \
            -f docker-compose.ci.yml \
            run --rm \
            terraform ./scripts/infra apply
    fi
fi
