#!/bin/bash

set -e

if [[ -n "${FASTAI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Setup external project dependencies.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose \
            run --rm \
            terraform ./scripts/infra plan

        docker-compose \
            run --rm \
            terraform ./scripts/infra apply

        echo "Update complete!"
        echo "Wait a few minutes for the server to finish initializing, and then start developing."
    fi
fi
