#!/bin/bash

set -e

if [[ -n "${FASTAI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Setup external project dependencies.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose \
            run --rm \
            terraform ./scripts/infra plan

        docker-compose \
            run --rm \
            terraform ./scripts/infra apply

        INSTANCE_ID=$(docker-compose \
            run --rm --workdir "/usr/local/src/deployment/terraform" \
            --entrypoint terraform \
            terraform output instance_id | tr -d '\r')

        ssh -t ubuntu@$INSTANCE_PUBLIC_DNS cd fastai && \
                                              git pull;  \
                                              git checkout v0.7.2 && \
                                              conda env update

    fi
fi
